### ISSUE TITLE
Need help with loading dist.zip on lambda

### ISSUE THREAD

**Issue by adlqgn** [azerpas/anchor-protocol-monitor#1]
Hello,

This project looks amazing!

I have successfully created file "dist.zip" but am unable to run the created function in Lambda. 
I got this error :
```
{
  "errorType": "Runtime.HandlerNotFound",
  "errorMessage": "index.handler is undefined or not exported",
  "trace": [
    "Runtime.HandlerNotFound: index.handler is undefined or not exported",
    "    at Object.module.exports.load (/var/runtime/UserFunction.js:144:11)",
    "    at Object.<anonymous> (/var/runtime/index.js:43:30)",
    "    at Module._compile (internal/modules/cjs/loader.js:1063:30)",
    "    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)",
    "    at Module.load (internal/modules/cjs/loader.js:928:32)",
    "    at Function.Module._load (internal/modules/cjs/loader.js:769:14)",
    "    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)",
    "    at internal/main/run_main_module.js:17:47"
  ]
}
```

What am i doing wrong ? I uploaded the dist.zip using "Upload zip" in the function, couldn't find any Drag and drop feature..

Thanks for the help.

**Comment by azerpas** [comment]
Hi thanks! Try to set the "Handler" to `handler.handler` instead of `index.handler` inside the Runtime Settings. I will add it into the readme, thank you. 😊 
<img width="1224" alt="image" src="https://user-images.githubusercontent.com/19282069/114916496-26fc9c80-9e25-11eb-93ed-43d7b6da6c31.png">

**Comment by azerpas** [comment]
Added it to the [README.md](https://github.com/azerpas/anchor-protocol-monitor/blob/main/README.md), let me know @adlqgn 🙂

**Comment by adlqgn** [comment]
> Added it to the [README.md](https://github.com/azerpas/anchor-protocol-monitor/blob/main/README.md), let me know @adlqgn 🙂

Thanks it fixed my issue!
