### ISSUE TITLE
Undefined .env value: 'LAST_BALANCE'

### ISSUE THREAD

**Issue by adlqgn** [azerpas/anchor-protocol-monitor#2]
Hello again,

Is LAST_BALANCE a required env variable ?

I got this error :
```
{
  "errorType": "Error",
  "errorMessage": "Undefined .env value: 'LAST_BALANCE'",
  "trace": [
    "Error: Undefined .env value: 'LAST_BALANCE'",
    "    at Runtime.handler (/var/task/handler.js:18:15)",
    "    at Runtime.handleOnce (/var/runtime/Runtime.js:66:25)"
  ]
}
```

Thanks.

**Comment by azerpas** [comment]
Hello 👋,

Yes it is, it keeps track of the last balance fetched on the previous execution. Set it to your current balance in this format ex: `323.03` (a float number with a `.00` precision). On the next execution it will calculate the change and the difference with the last execution.

**Comment by adlqgn** [comment]
Thanks, all good now!
